language: python
sudo: false
python:
  - "3.6"
services:
  - docker
install:
  - chmod 777 -R "$(pwd)"
script:
  - make dep
  - make lint
  - make test
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -f .pycoverage/pycov.xml -t f5022fb6-e891-4d19-babd-791ab1909bed