#!/usr/bin/env bash

CONFIG=$1
OUTDIR=$2
STD_TEMPLATE=$3

while getopts c:o:s: option
do
case "${option}"
in
c) CONFIG=${OPTARG};;
o) OUTDIR=${OPTARG};;
s) STD_TEMPLATE=${OPTARG};;
esac
done



python3 -m pkg.ccextender.ccextender