#!/usr/bin/env bash

CONFIG="None"
OUTDIR="."

while getopts c:o: option
do
case "${option}"
in
c) CONFIG=${OPTARG};;
o) OUTDIR=${OPTARG};;
esac
done



python3 -m pkg.ccextender.ccextender -c $CONFIG -o $OUTDIR