CCX_Version: 1.0
standard-context:
  project_name: "My SecDev OSS Project"
  project_slug: "my-secdev-oss-project"
  project_description: "A new SecDev project created with CCExtender"
  project_namespace: "asecurityteam"
  notification_email: "aslape@atlassian.com"
decisions:
  gateway:
    query:
      prompt: "Would you like to [1] install a gateway image?"
    gateway:
      - gateway
change-packs:
  gateway:
    template-gateway:
      image_name: "Placeholder"
locations:
  home:
    - pkg/ccextender/configs/
  template-gateway:
    - $!home$
    - template-gateway/
  template-standards:
    - $!home$
    - template-standards/

